apiVersion: v1
kind: Service
metadata:
  name: todolist-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: todolist-app
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30100